setono_sylius_job_status_admin_job:
    resource: |
        section: admin
        alias: setono_sylius_job_status.job
        templates: "@SyliusAdmin\\Crud"
        permission: true
        only: ['index']
        grid: setono_sylius_job_status_admin_job
        vars:
            all:
                header: setono_sylius_job_status.ui.job_header
                subheader: setono_sylius_job_status.ui.job_subheader
    type: sylius.resource
