imports:
    - { resource: "@SetonoSyliusJobStatusPlugin/Resources/config/grids/setono_sylius_job_status_admin_job.yaml" }

sylius_ui:
    events:
        setono_sylius_job_status.admin.job.index.javascripts:
            blocks:
                progress_javascript: '@SetonoSyliusJobStatusPlugin/admin/progress_javascript.html.twig'
